import profile_pic_1 from "../assets/img/profile_pic_1.jpg";
import profile_pic_2 from "../assets/img/profile_pic_2.jpg";
import profile_pic_3 from "../assets/img/profile_pic_3.jpg";
export const state = {
  overView: [
    { value: "$16,034", text: "Total borrowed amount" },
    { value: "$160,032", text: "Total supplied amount" },
    { value: "32%", text: "Total borrow rate" },
    { value: "15%", text: "Total lending rate" },
  ],
  deposit: [
    { value: "$0", text: "Deposited" },
    { value: "$0", text: "Interest Earned" },
    { value: "6%", text: "Interest Rate" },
  ],
  credit: [
    { value: "$0", text: "Credit Granted" },
    { value: "$0", text: "Active Credit" },
    { value: "0", text: "Interest Accrued" },
    { value: "6%", text: "Interest Rate" },
  ],
  poolCards: [
    {
      tag1: "Open Pool",
      tag2: "Grace Period",
      borrowRate: "11%",
      borrowAmount: "1,000 DOT",
      thirdItem: "Next Payment",
      thirdValue: "200 DOT",
      percentage: "45%",
      fourthItem: "Repayment Progress",
      btnColor: "bg-yellow-200",
      btnText: "Repay",
      fifthItem: "",
      fifthValue: "",
    },
    {
      tag1: "Open Borrow",
      tag2: "Collecting",
      borrowRate: "200 DOT",
      borrowAmount: "1,000 DOT",
      thirdItem: "",
      thirdValue: "",
      fifthItem: "Ends in",
      fifthValue: "2d 12h 34m",
      percentage: "45%",
      fourthItem: "Collection Progress",
      btnColor: "bg-gray-200",
      btnText: "Add collateral",
    },
    {
      tag1: "Open Borrow",
      tag2: "Closed",
      borrowRate: "200 DOT",
      borrowAmount: "1,000 DOT",
      thirdItem: "",
      thirdValue: "",
      fifthItem: "Ended on",
      fifthValue: "30th Jan 2021",
      percentage: "100%",
      fourthItem: "Repayment Progress",
      btnColor: "bg-gray-200",
      btnText: "View more",
    },
    {
      tag1: "Open Borrow",
      tag2: "Closed",
      borrowRate: "11%",
      borrowAmount: "1,000 DOT",
      thirdItem: "",
      thirdValue: "",
      fifthItem: "Ended on",
      fifthValue: "30th Jan 2021",
      percentage: "100%",
      fourthItem: "Repayment Progress",
      btnColor: "bg-gray-200",
      btnText: "View more",
    },
    {
      tag1: "private",
      tag2: "Closed",
      borrowRate: "11%",
      borrowAmount: "1,000 DOT",
      thirdItem: "",
      thirdValue: "",
      fifthItem: "Ended on",
      fifthValue: "30th Jan 2021",
      percentage: "100%",
      fourthItem: "Repayment Progress",
      btnColor: "bg-gray-200",
      btnText: "View more",
    },
  ],
};

export const IMPORTANT = [
  {
    src: profile_pic_1,
    secondary: "@Lorem_ipsum",
    subText: "vote ends in 2 days",
  },
  {
    src: profile_pic_2,
    secondary: "@Lorem_ipsum",
    subText: "vote ends in 2 days",
  },
  {
    src: profile_pic_3,
    secondary: "@Lorem_ipsum",
    subText: "vote ends in 2 days",
  },
];
